### ISSUE TITLE
Put emoji to right position where cursor is on.

### ISSUE THREAD

**Issue by yumere** [se0kjun/github-forget-emoji#1]
Now, Putting emoji just add to last of sentence.

:trollface:

**Comment by kyeongmincho** [comment]
I'll give u 1 DDabong :+1:

**Comment by se0kjun** [comment]
:smiley_cat::smiley_cat::smiley_cat:

ddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddd

**Comment by yumere** [comment]
@se0kjun 

Good, Work very well.

When you're satisfied perfectly, close yourself(#1).
